# Generated by Django 3.2.7 on 2023-06-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('metascore', models.FloatField()),
                ('user_score', models.FloatField()),
                ('metascore_count', models.IntegerField()),
                ('user_rating_count', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('critic_reviews', models.TextField()),
            ],
        ),
    ]
